# Generated by Django 2.2 on 2022-03-30 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('ownername', models.CharField(max_length=30)),
                ('ownerphone', models.CharField(max_length=30)),
                ('owneremail', models.CharField(max_length=30)),
                ('temperature', models.FloatField(default=0)),
                ('loads', models.CharField(max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
